from tkinter import *

root = Tk()

myLabel = Label(root, text="Hello World!")
myLabel1 = Label(root, text="Hello World!")
myLabel2 = Label(root, text="Hello World!")
myLabel3 = Label(root, text="Hello World!")
myLabel4 = Label(root, text="Hello World!")
myLabel5 = Label(root, text="Hello World!")
myLabel6 = Label(root, text="Hello World!")
myLabel7 = Label(root, text="Hello World!")
myLabel8 = Label(root, text="Hello World!")
myLabel9 = Label(root, text="Hello World!")
myLabel.pack()
myLabel1.pack()
myLabel2.pack()
myLabel3.pack()
myLabel4.pack()
myLabel5.pack()
myLabel6.pack()
myLabel7.pack()
myLabel8.pack()
myLabel9.pack()
root.mainloop()
